# Generated by Django 5.1.15 on 2026-04-01 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPickerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Питання')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Питання підбору подарунку',
                'verbose_name_plural': 'Питання підбору подарунку',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GiftPickerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Варіант відповіді')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Мін. ціна')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Макс. ціна')),
                ('categories', models.ManyToManyField(blank=True, to='products.category', verbose_name='Категорії')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='promotions.giftpickerquestion', verbose_name='Питання')),
            ],
            options={
                'verbose_name': 'Варіант відповіді',
                'verbose_name_plural': 'Варіанти відповідей',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва акції')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('start_date', models.DateTimeField(verbose_name='Початок')),
                ('end_date', models.DateTimeField(verbose_name='Кінець')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Акція',
                'verbose_name_plural': 'Акції',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='UpsellGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва групи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('suggested_products', models.ManyToManyField(blank=True, related_name='upsell_suggestions', to='products.product', verbose_name='Рекомендовані товари')),
                ('trigger_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_triggers', to='products.product', verbose_name='Товар-тригер')),
            ],
            options={
                'verbose_name': 'Upsell група',
                'verbose_name_plural': 'Upsell групи',
            },
        ),
    ]
