# Generated by Django 5.1.15 on 2026-04-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(help_text='Дата і час завершення. Таймер на сторінці товару показує залишок до цього моменту.', verbose_name='Кінець'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Якщо вимкнено — акція не показується незалежно від дат.', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(help_text='Дата і час, коли акція починається.', verbose_name='Початок'),
        ),
    ]
