# Generated by Django 5.1.15 on 2026-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotion_end_date_alter_promotion_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpickeroption',
            name='text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Варіант відповіді'),
        ),
        migrations.AddField(
            model_name='giftpickeroption',
            name='text_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Варіант відповіді'),
        ),
        migrations.AddField(
            model_name='giftpickeroption',
            name='text_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Варіант відповіді'),
        ),
        migrations.AddField(
            model_name='giftpickerquestion',
            name='text_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Питання'),
        ),
        migrations.AddField(
            model_name='giftpickerquestion',
            name='text_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Питання'),
        ),
        migrations.AddField(
            model_name='giftpickerquestion',
            name='text_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Питання'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва акції'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва акції'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва акції'),
        ),
    ]
