# Generated by Django 5.1.15 on 2026-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва шаблону')),
                ('meta_title_template', models.CharField(help_text='Доступні змінні: {name}, {category}, {price}, {site_name}', max_length=300, verbose_name='Шаблон title')),
                ('meta_description_template', models.TextField(help_text='Доступні змінні: {name}, {category}, {price}, {site_name}', verbose_name='Шаблон description')),
            ],
            options={
                'verbose_name': 'SEO шаблон',
                'verbose_name_plural': 'SEO шаблони',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Магазин книжок', max_length=200, verbose_name='Назва сайту')),
                ('site_description', models.TextField(blank=True, verbose_name='Опис сайту')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='Favicon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адреса')),
                ('phone_1', models.CharField(blank=True, max_length=30, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(blank=True, max_length=30, verbose_name='Телефон 2')),
                ('phone_3', models.CharField(blank=True, max_length=30, verbose_name='Телефон 3')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('viber_url', models.URLField(blank=True, verbose_name='Viber')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('promo_banner_text', models.CharField(blank=True, max_length=300, verbose_name='Промо-банер текст')),
                ('promo_banner_url', models.URLField(blank=True, verbose_name='Промо-банер посилання')),
                ('seo_home_title', models.CharField(blank=True, max_length=200, verbose_name='SEO title головної')),
                ('seo_home_description', models.TextField(blank=True, verbose_name='SEO description головної')),
                ('work_schedule', models.TextField(blank=True, default='Пн-Пт: 09:00-19:00\nСб-Нд: 10:00-18:00', verbose_name='Графік роботи')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактна особа')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
