# Generated by Django 5.1.15 on 2026-04-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_online_consultant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='return_policy',
            field=models.TextField(blank=True, default='Повернення можливе протягом 14 днів після отримання (для товарів належної якості).', verbose_name='Умови повернення та обміну'),
        ),
    ]
