# Generated by Django 5.1.15 on 2026-04-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_return_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва (для адмінки)')),
                ('image', models.ImageField(help_text='Десктоп: 1280×360 px (або 1920×540 px); мобільний: 720×360 px. JPG/WEBP.', upload_to='banners/', verbose_name='Зображення')),
                ('image_mobile', models.ImageField(blank=True, help_text="Необов'язково. Якщо порожньо — використовується основне зображення.", upload_to='banners/', verbose_name='Зображення (моб.)')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('link', models.URLField(blank=True, verbose_name='Посилання')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Відкривати в новій вкладці')),
                ('position', models.CharField(choices=[('home_hero', 'Головна — головний банер'), ('home_middle', 'Головна — посередині сторінки'), ('home_bottom', 'Головна — унизу сторінки'), ('catalog_top', 'Каталог — над списком товарів'), ('product_bottom', 'Сторінка товару — унизу'), ('footer_top', 'Над футером')], default='home_hero', max_length=30, verbose_name='Розташування')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('start_date', models.DateTimeField(blank=True, help_text='Якщо порожньо — показується одразу.', null=True, verbose_name='Початок показу')),
                ('end_date', models.DateTimeField(blank=True, help_text='Якщо порожньо — показується без обмеження часу.', null=True, verbose_name='Кінець показу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
                'ordering': ['position', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Наприклад: about, delivery, payment, returns. Використовується у посиланнях.', max_length=100, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, help_text='Підтримує HTML (абзаци, списки, акценти).', verbose_name='Контент')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('show_in_footer', models.BooleanField(default=True, help_text="Якщо увімкнено — посилання з'явиться у блоці «Інформація» у футері.", verbose_name='Показувати у футері')),
                ('footer_order', models.PositiveIntegerField(default=0, verbose_name='Порядок у футері')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Сторінки',
                'ordering': ['footer_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір: 64×64 px або 32×32 px (PNG/ICO).', upload_to='site/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір: 200×80 px (PNG/SVG, прозорий фон).', upload_to='site/', verbose_name='Логотип'),
        ),
    ]
