# Generated by Django 5.1.15 on 2026-04-26 10:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_banner_page_sitesettings_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='Підтримує форматування: абзаци, списки, акценти, посилання.', verbose_name='Контент'),
        ),
    ]
