# Generated by Django 5.1.15 on 2026-04-26 10:18

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, verbose_name='Питання')),
                ('answer', tinymce.models.HTMLField(verbose_name='Відповідь')),
                ('scope', models.CharField(choices=[('global', 'Глобальний (на всіх сторінках товарів та статей)'), ('product', 'Лише на сторінках товарів'), ('blog', 'Лише на сторінках статей/новин'), ('page', 'Лише на текстових сторінках')], default='global', max_length=20, verbose_name='Розташування')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'id'],
            },
        ),
    ]
