# Generated by Django 5.1.15 on 2026-04-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(blank=True, help_text='HEX, наприклад #c9a25b. Кнопки, ціни, акценти.', max_length=20, verbose_name='Акцентний колір'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bg_color',
            field=models.CharField(blank=True, help_text='HEX, наприклад #0a0a0a.', max_length=20, verbose_name='Колір фону сайту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_ads_conversion_id',
            field=models.CharField(blank=True, help_text='Наприклад: AW-123456789. Для відстеження конверсій реклами.', max_length=50, verbose_name='Google Ads Conversion ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Наприклад: G-XXXXXXXXXX. Якщо задано — підключається gtag.js.', max_length=50, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='Наприклад: GTM-XXXXXXX. Якщо задано — підключається GTM скрипт.', max_length=50, verbose_name='Google Tag Manager ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(blank=True, help_text='HEX, наприклад #0d0d0d. Якщо порожньо — використовується дефолт.', max_length=20, verbose_name='Основний колір'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_color',
            field=models.CharField(blank=True, help_text='HEX, наприклад #ececec.', max_length=20, verbose_name='Колір тексту'),
        ),
    ]
