# Generated by Django 5.1.15 on 2026-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_accent_color_sitesettings_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_en',
            field=models.BooleanField(default=False, verbose_name='Увімкнути англійську'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_ru',
            field=models.BooleanField(default=False, verbose_name='Увімкнути російську'),
        ),
    ]
