# Generated by Django 5.1.15 on 2026-04-28 09:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_enable_en_sitesettings_enable_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='banner',
            name='alt_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='banner',
            name='alt_text_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Відповідь'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Відповідь'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uk',
            field=tinymce.models.HTMLField(null=True, verbose_name='Відповідь'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Питання'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Питання'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uk',
            field=models.CharField(max_length=400, null=True, verbose_name='Питання'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, help_text='Підтримує форматування: абзаци, списки, акценти, посилання.', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=tinymce.models.HTMLField(blank=True, help_text='Підтримує форматування: абзаци, списки, акценти, посилання.', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_uk',
            field=tinymce.models.HTMLField(blank=True, help_text='Підтримує форматування: абзаци, списки, акценти, посилання.', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='meta_description_template_en',
            field=models.TextField(help_text='Доступні змінні: {name}, {category}, {price}, {site_name}', null=True, verbose_name='Шаблон description'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='meta_description_template_ru',
            field=models.TextField(help_text='Доступні змінні: {name}, {category}, {price}, {site_name}', null=True, verbose_name='Шаблон description'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='meta_description_template_uk',
            field=models.TextField(help_text='Доступні змінні: {name}, {category}, {price}, {site_name}', null=True, verbose_name='Шаблон description'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='meta_title_template_en',
            field=models.CharField(help_text='Доступні змінні: {name}, {category}, {price}, {site_name}', max_length=300, null=True, verbose_name='Шаблон title'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='meta_title_template_ru',
            field=models.CharField(help_text='Доступні змінні: {name}, {category}, {price}, {site_name}', max_length=300, null=True, verbose_name='Шаблон title'),
        ),
        migrations.AddField(
            model_name='seotemplate',
            name='meta_title_template_uk',
            field=models.CharField(help_text='Доступні змінні: {name}, {category}, {price}, {site_name}', max_length=300, null=True, verbose_name='Шаблон title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_banner_text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Промо-банер текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_banner_text_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Промо-банер текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_banner_text_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Промо-банер текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_home_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description головної'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_home_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description головної'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_home_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='SEO description головної'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_home_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO title головної'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_home_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO title головної'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_home_title_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO title головної'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис сайту (головна)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис сайту (головна)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description_uk',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис сайту (головна)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Опис сайту (головна)'),
        ),
    ]
