# Generated by Django 5.1.15 on 2026-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='header_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок у хедері'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_header',
            field=models.BooleanField(default=False, help_text="Якщо увімкнено — посилання з'явиться в навігаційному рядку хедера.", verbose_name='Показувати у хедері'),
        ),
    ]
