# Generated by Django 5.1.15 on 2026-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('content', models.TextField(verbose_name='Контент')),
                ('excerpt', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('image', models.ImageField(blank=True, upload_to='blog/articles/', verbose_name='Зображення')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('content', models.TextField(verbose_name='Контент')),
                ('excerpt', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('image', models.ImageField(blank=True, upload_to='blog/news/', verbose_name='Зображення')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ['-created_at'],
            },
        ),
    ]
