# Generated by Django 5.1.15 on 2026-04-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір: 1200×675 px (співвідношення 16:9), JPG/WEBP.', upload_to='blog/articles/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір: 1200×675 px (співвідношення 16:9), JPG/WEBP.', upload_to='blog/news/', verbose_name='Зображення'),
        ),
    ]
