# Generated by Django 5.1.15 on 2026-04-28 09:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_content_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_uk',
            field=tinymce.models.HTMLField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt_en',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uk',
            field=tinymce.models.HTMLField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_en',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_title_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
    ]
