# Generated by Django 5.1.15 on 2026-04-01 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=150, verbose_name='Прізвище')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='По батькові')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=200, verbose_name='Місто')),
                ('warehouse', models.CharField(max_length=300, verbose_name='Відділення НП')),
                ('warehouse_ref', models.CharField(blank=True, max_length=100, verbose_name='Ref відділення')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('payment_method', models.CharField(choices=[('liqpay', 'LiqPay'), ('monobank', 'Monobank'), ('cod', 'Накладений платіж')], default='cod', max_length=20, verbose_name='Спосіб оплати')),
                ('payment_status', models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('failed', 'Помилка оплати'), ('refunded', 'Повернення')], default='pending', max_length=20, verbose_name='Статус оплати')),
                ('payment_id', models.CharField(blank=True, max_length=200, verbose_name='ID платежу')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сума')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=400, verbose_name='Назва товару')),
                ('product_sku', models.CharField(max_length=50, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар замовлення',
                'verbose_name_plural': 'Товари замовлення',
            },
        ),
    ]
