# Generated by Django 5.1.15 on 2026-05-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('liqpay', 'LiqPay'), ('monobank', 'Monobank'), ('cod', 'Накладений платіж'), ('manager', "Зв'яжіться з менеджером")], default='cod', max_length=20, verbose_name='Спосіб оплати'),
        ),
    ]
