# Generated by Django 5.1.15 on 2026-04-01 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Зображення')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=400, unique=True, verbose_name='URL')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('description', models.TextField(verbose_name='Опис')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стара ціна')),
                ('stock_status', models.CharField(choices=[('in_stock', 'В наявності'), ('ready', 'Готово до відправки'), ('order', 'Під замовлення'), ('out', 'Немає в наявності')], default='in_stock', max_length=20, verbose_name='Наявність')),
                ('badge', models.CharField(blank=True, choices=[('', '---'), ('sale', 'Акція'), ('top', 'Топ продажів'), ('new', 'Новинка')], default='', max_length=20, verbose_name='Бейдж')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Знижка %')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Виробник')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Країна')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вага (кг)')),
                ('condition', models.CharField(default='Новий', max_length=50, verbose_name='Стан')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('value', models.CharField(max_length=400, verbose_name='Значення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товарів',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, verbose_name='URL відео (YouTube/Vimeo)')),
                ('video_file', models.FileField(blank=True, upload_to='products/videos/', verbose_name='Файл відео')),
                ('poster', models.ImageField(blank=True, upload_to='products/posters/', verbose_name='Постер')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Відео товару',
                'verbose_name_plural': 'Відео товарів',
                'ordering': ['order'],
            },
        ),
    ]
