# Generated by Django 5.1.15 on 2026-04-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Стан'),
        ),
    ]
