# Generated by Django 5.1.15 on 2026-04-26 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Латиницею, без пробілів. Наприклад: sale, top, new, gift.', max_length=40, unique=True, verbose_name='Код')),
                ('name', models.CharField(help_text='Текст, який видно на товарі.', max_length=100, verbose_name='Назва')),
                ('color', models.CharField(choices=[('red', 'Червоний'), ('orange', 'Помаранчевий'), ('yellow', 'Жовтий'), ('green', 'Зелений'), ('blue', 'Синій'), ('purple', 'Фіолетовий'), ('pink', 'Рожевий'), ('gold', 'Золотий'), ('black', 'Чорний')], default='red', help_text='Виберіть колір фону бейджа.', max_length=20, verbose_name='Колір')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Бейдж',
                'verbose_name_plural': 'Бейджі',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендований розмір: 600×450 px (співвідношення 4:3), JPG/WEBP.', upload_to='categories/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('', '---'), ('sale', 'Акція'), ('top', 'Топ продажів'), ('new', 'Новинка')], default='', help_text='Залишено для зворотної сумісності. Використовуйте поле «Бейдж (новий)».', max_length=20, verbose_name='Бейдж (старий)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Рекомендований розмір: 1000×1000 px (квадрат), JPG/WEBP, до 1.5 МБ.', upload_to='products/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.badge', verbose_name='Бейдж'),
        ),
    ]
