# Generated by Django 5.1.15 on 2026-04-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_description_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku_manufacturer',
            field=models.CharField(blank=True, help_text='Заводський / код постачальника. Бачать лише адміністратори.', max_length=100, verbose_name='Артикул виробника'),
        ),
    ]
