# Generated by Django 5.1.15 on 2026-04-28 09:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_sku_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='name_en',
            field=models.CharField(help_text='Текст, який видно на товарі.', max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='badge',
            name='name_ru',
            field=models.CharField(help_text='Текст, який видно на товарі.', max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='badge',
            name='name_uk',
            field=models.CharField(help_text='Текст, який видно на товарі.', max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=tinymce.models.HTMLField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=400, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_uk',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Значення'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Значення'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_uk',
            field=models.CharField(max_length=400, null=True, verbose_name='Значення'),
        ),
    ]
